#!/bin/bash
# Script para fazer deploy no Vercel com Supabase
# Configure as variáveis de ambiente ANTES de executar este script

echo "📋 Configurando variáveis de ambiente no Vercel..."
echo ""
echo "⚠️  IMPORTANTE: Você precisa adicionar estas variáveis no Vercel Dashboard"
echo ""
echo "1. Acesse: https://vercel.com/dashboard"
echo "2. Selecione seu projeto 'painelbm'"
echo "3. Vá para Settings → Environment Variables"
echo "4. Adicione as seguintes variáveis:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "NEXT_PUBLIC_SUPABASE_URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "SUPABASE_SERVICE_ROLE_KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo ""
echo "✅ Após adicionar as variáveis:"
echo ""
echo "1. Clique em 'Redeploy' seu projeto"
echo "2. Aguarde ~2-3 minutos"
echo "3. Acesse https://painelbm.vercel.app"
echo "4. Teste as edições que agora devem persistir em produção!"
echo ""
echo "📝 As chaves já estão em seu .env.local (arquivo local)"
